// src/utils/audioMap.js
// AUTO-GENERATED by scripts/generate_audio.js — do not edit by hand.
// Run `npm run generate-audio` to regenerate (requires an ElevenLabs API
// key). This module ships with no pre-generated audio: if a narration
// line isn't found here, useAudio() silently skips it rather than
// falling back to browser text-to-speech.
export const audioMap = {};
