// src/utils/audioMap.js
// AUTO-GENERATED by scripts/generate_audio.js — do not edit by hand.
// Run `npm run generate-audio` to regenerate.

export const audioMap = {
  "If you had 47 stars, could you write that number in words instead of digits?": "assets/audio/audio_if_you_had_47_stars_could_you_write_that_number_in_word_0.mp3",
  "What if there's a secret code that turns numbers into words?": "assets/audio/audio_what_if_theres_a_secret_code_that_turns_numbers_into_wo_1.mp3",
  "What if numbers could talk? What would sixty-seven look like written down?": "assets/audio/audio_what_if_numbers_could_talk_what_would_sixtyseven_look_l_2.mp3",
  "Every number has a name, and a hidden shape made of tens and ones.": "assets/audio/audio_every_number_has_a_name_and_a_hidden_shape_made_of_tens_3.mp3",
  "Can you guess how many blocks are hiding inside the number 83?": "assets/audio/audio_can_you_guess_how_many_blocks_are_hiding_inside_the_num_4.mp3",
  "Numbers are like treasure chests -- let's open one and see what's inside.": "assets/audio/audio_numbers_are_like_treasure_chests_lets_open_one_and_see__5.mp3",
  "If someone gave you twenty-five candies, how would you count them super fast?": "assets/audio/audio_if_someone_gave_you_twentyfive_candies_how_would_you_co_6.mp3",
  "There's a magical trick using groups of ten.": "assets/audio/audio_theres_a_magical_trick_using_groups_of_ten_7.mp3",
  "What comes after ninety-nine? And how do we write it?": "assets/audio/audio_what_comes_after_ninetynine_and_how_do_we_write_it_8.mp3",
  "The biggest number we'll explore today has a very special name.": "assets/audio/audio_the_biggest_number_well_explore_today_has_a_very_specia_9.mp3",
  "One sunny morning, Wei Ming walked into the school library. He loved books, especially about dinosaurs! He looked around at the tall shelves full of colourful books and wondered how many were on just one shelf.": "assets/audio/audio_one_sunny_morning_wei_ming_walked_into_the_school_libra_10.mp3",
  "The librarian smiled and said, we have forty-two books about dinosaurs! Wei Ming was puzzled. Forty-two? That sounded like a lot, but what did forty-two really mean?": "assets/audio/audio_the_librarian_smiled_and_said_we_have_fortytwo_books_ab_11.mp3",
  "Then his classmate Priya showed him a trick! She grouped 4 bundles of ten books and 2 single books. Look, she said, 4 tens and 2 ones make 42! Suddenly, the number made perfect sense.": "assets/audio/audio_then_his_classmate_priya_showed_him_a_trick_she_grouped_12.mp3",
  "Wei Ming grinned. Now he could read and write any number from zero all the way to one hundred! Can we practise more, he asked Bintang the bear. And so, the number adventure began.": "assets/audio/audio_wei_ming_grinned_now_he_could_read_and_write_any_number_13.mp3",
  "Star Counting Mission!": "assets/audio/audio_star_counting_mission_14.mp3",
  "Tap the ten-frame to fill in exactly the right number of stars.": "assets/audio/audio_tap_the_tenframe_to_fill_in_exactly_the_right_number_of_15.mp3",
  "Toy Box Mission!": "assets/audio/audio_toy_box_mission_16.mp3",
  "Build teen numbers as one full ten, plus a few extra ones.": "assets/audio/audio_build_teen_numbers_as_one_full_ten_plus_a_few_extra_one_17.mp3",
  "Block Builder Mission!": "assets/audio/audio_block_builder_mission_18.mp3",
  "Use the tens and ones controls to build each number with base-ten blocks.": "assets/audio/audio_use_the_tens_and_ones_controls_to_build_each_number_wit_19.mp3",
  "Word Match Mission!": "assets/audio/audio_word_match_mission_20.mp3",
  "Tap a numeral, then tap its matching number word.": "assets/audio/audio_tap_a_numeral_then_tap_its_matching_number_word_21.mp3",
  "Boss battle time! Answer every question correctly to win.": "assets/audio/audio_boss_battle_time_answer_every_question_correctly_to_win_22.mp3",
  "Remember: break each number into tens and ones, then count up.": "assets/audio/audio_remember_break_each_number_into_tens_and_ones_then_coun_23.mp3",
  "Boss defeated! Fantastic number reading!": "assets/audio/audio_boss_defeated_fantastic_number_reading_24.mp3",
  "Great match!": "assets/audio/audio_great_match_25.mp3",
  "Not quite a match -- try again!": "assets/audio/audio_not_quite_a_match_try_again_26.mp3",
};
